# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2014-2026 William Edwards <shadowapex@gmail.com>, Benjamin Bean <superman2k5@gmail.com>
"""
Validator-backed New Campaign Wizard prototype.

Implements the 4-step wizard described in docs/campaign_maker_mvp.md §5.
Each step is validated independently before the wizard advances.
The final step produces a CampaignManifest and optionally generates
the scaffold directory structure on disk.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from pydantic import ValidationError

from tuxemon.campaign.models import (
    CampaignManifest,
    CampaignRulesetOverride,
    ScaffoldDirectory,
    WizardStep1,
    WizardStep2,
    WizardStep3,
)

logger = logging.getLogger(__name__)

ENGINE_VERSION = "0.4.35"

# Scaffold subdirectories to create for every new campaign.
_SCAFFOLD_SUBDIRS = [
    "maps",
    "scripts",
    "monsters",
    "items",
    "music",
    "sounds",
    "gfx",
    "locale",
]

# Placeholder content for required scaffold files.
_PLACEHOLDER_START_MAP = "start.tmx"
_PLACEHOLDER_ENTRY_SCRIPT = "main_intro"

_MANIFEST_TEMPLATE = """\
# campaign.yaml — generated by OpenCapsuleMon Campaign Wizard
id: "{id}"
name: "{name}"
version: "1.0.0"
author: "{author}"
engine_min_version: "{engine_min_version}"
description: "{description}"
start_map: "maps/{start_map}"
entry_script: "{entry_script}"
language: "en_US"
"""


class WizardValidationError(Exception):
    """Raised when a wizard step fails validation."""

    def __init__(self, step: int, errors: list[dict]) -> None:
        self.step = step
        self.errors = errors
        super().__init__(f"Step {step} validation failed: {errors}")


class CampaignWizard:
    """
    Stateful four-step campaign creation wizard.

    Usage::

        wizard = CampaignWizard()
        wizard.submit_step1(id="my_campaign", name="My Campaign",
                            author="Me", description="A great adventure.")
        wizard.submit_step2(template="blank")
        wizard.submit_step3(default_difficulty="normal")
        manifest = wizard.build_manifest()
        scaffold = wizard.generate_scaffold(Path("~/campaigns/my_campaign"))
    """

    def __init__(self) -> None:
        self._step1: Optional[WizardStep1] = None
        self._step2: Optional[WizardStep2] = None
        self._step3: Optional[WizardStep3] = None

    # ------------------------------------------------------------------
    # Step submission
    # ------------------------------------------------------------------

    def submit_step1(
        self,
        id: str,
        name: str,
        author: str,
        description: str,
    ) -> WizardStep1:
        """
        Validate and record Step 1 (Campaign Identity).

        Raises WizardValidationError on invalid input.
        Returns the validated WizardStep1 model.
        """
        try:
            step = WizardStep1(
                id=id,
                name=name,
                author=author,
                description=description,
            )
        except ValidationError as exc:
            raise WizardValidationError(1, exc.errors()) from exc
        self._step1 = step
        logger.debug("Wizard step 1 accepted: id=%s", id)
        return step

    def submit_step2(self, template: str = "blank") -> WizardStep2:
        """
        Validate and record Step 2 (Starting Point).

        Raises WizardValidationError on invalid template.
        Returns the validated WizardStep2 model.
        """
        self._require_step(1)
        try:
            step = WizardStep2(template=template)
        except ValidationError as exc:
            raise WizardValidationError(2, exc.errors()) from exc
        self._step2 = step
        logger.debug("Wizard step 2 accepted: template=%s", template)
        return step

    def submit_step3(
        self,
        default_difficulty: str = "normal",
        permadeath: bool = False,
        nuzlocke_mode: bool = False,
        active_clauses: Optional[list[str]] = None,
    ) -> WizardStep3:
        """
        Validate and record Step 3 (Rules and Difficulty).

        Raises WizardValidationError on invalid rules.
        Returns the validated WizardStep3 model.
        """
        self._require_step(2)
        try:
            step = WizardStep3(
                default_difficulty=default_difficulty,
                permadeath=permadeath,
                nuzlocke_mode=nuzlocke_mode,
                active_clauses=active_clauses or [],
            )
        except ValidationError as exc:
            raise WizardValidationError(3, exc.errors()) from exc
        self._step3 = step
        logger.debug(
            "Wizard step 3 accepted: difficulty=%s", default_difficulty
        )
        return step

    # ------------------------------------------------------------------
    # Manifest construction
    # ------------------------------------------------------------------

    def build_manifest(self) -> CampaignManifest:
        """
        Construct the final CampaignManifest from all completed wizard steps.

        All three steps must have been submitted before calling this method.
        Raises WizardValidationError if the assembled manifest fails validation.
        """
        self._require_step(3)
        assert self._step1 is not None
        assert self._step2 is not None
        assert self._step3 is not None

        ruleset = CampaignRulesetOverride(
            default_difficulty=self._step3.default_difficulty,
            permadeath=self._step3.permadeath,
            nuzlocke_mode=self._step3.nuzlocke_mode,
            active_clauses=self._step3.active_clauses or None,
        )

        try:
            manifest = CampaignManifest(
                id=self._step1.id,
                name=self._step1.name,
                version="1.0.0",
                author=self._step1.author,
                engine_min_version=ENGINE_VERSION,
                description=self._step1.description,
                start_map=f"maps/{_PLACEHOLDER_START_MAP}",
                entry_script=_PLACEHOLDER_ENTRY_SCRIPT,
                ruleset=ruleset,
            )
        except ValidationError as exc:
            raise WizardValidationError(4, exc.errors()) from exc

        logger.info("Campaign manifest built: id=%s", manifest.id)
        return manifest

    # ------------------------------------------------------------------
    # Scaffold generation
    # ------------------------------------------------------------------

    def generate_scaffold(
        self, output_dir: Path, *, dry_run: bool = False
    ) -> ScaffoldDirectory:
        """
        Generate the campaign scaffold directory structure on disk.

        Parameters
        ----------
        output_dir:
            The directory to create. Must not already exist.
        dry_run:
            If True, return the ScaffoldDirectory descriptor without
            creating any files or directories on disk. Useful for testing.

        Returns the ScaffoldDirectory descriptor.
        Raises FileExistsError if output_dir already exists (and not dry_run).
        """
        manifest = self.build_manifest()
        scaffold = ScaffoldDirectory.from_root(output_dir)

        if dry_run:
            return scaffold

        if output_dir.exists():
            raise FileExistsError(
                f"Campaign directory already exists: {output_dir}"
            )

        output_dir.mkdir(parents=True)
        for subdir in _SCAFFOLD_SUBDIRS:
            (output_dir / subdir).mkdir()

        manifest_text = _MANIFEST_TEMPLATE.format(
            id=manifest.id,
            name=manifest.name,
            author=manifest.author,
            engine_min_version=manifest.engine_min_version,
            description=manifest.description,
            start_map=_PLACEHOLDER_START_MAP,
            entry_script=_PLACEHOLDER_ENTRY_SCRIPT,
        )
        scaffold.manifest_path.write_text(manifest_text, encoding="utf-8")

        logger.info(
            "Campaign scaffold generated at %s (id=%s)",
            output_dir,
            manifest.id,
        )
        return scaffold

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _require_step(self, step: int) -> None:
        steps = {1: self._step1, 2: self._step2, 3: self._step3}
        if steps[step] is None:
            raise RuntimeError(
                f"Step {step} has not been submitted. "
                f"Complete wizard steps in order (1 → 2 → 3)."
            )

    @property
    def completed_steps(self) -> list[int]:
        """Return the list of step numbers that have been submitted."""
        result = []
        if self._step1 is not None:
            result.append(1)
        if self._step2 is not None:
            result.append(2)
        if self._step3 is not None:
            result.append(3)
        return result

    def reset(self) -> None:
        """Clear all step data and return the wizard to its initial state."""
        self._step1 = None
        self._step2 = None
        self._step3 = None
