# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2014-2026 William Edwards <shadowapex@gmail.com>, Benjamin Bean <superman2k5@gmail.com>
"""
Base class for campaign templates.

A CampaignTemplate knows how to populate a scaffold directory with
pre-authored content files (TMX maps, event scripts, encounter tables,
locale strings). The base implementation writes nothing; subclasses
override apply() to add their content.
"""
from __future__ import annotations

import logging
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Minimal valid Tiled TMX map template (XML)
_TMX_TEMPLATE = textwrap.dedent("""\
    <?xml version="1.0" encoding="UTF-8"?>
    <map version="1.10" tiledversion="1.11.0" orientation="orthogonal"
         renderorder="right-down" compressionlevel="0"
         width="{width}" height="{height}"
         tilewidth="16" tileheight="16" infinite="0"
         nextlayerid="5" nextobjectid="10">
     <properties>
      <property name="slug" value="{slug}"/>
      <property name="map_type" value="campaign"/>
     </properties>
     <layer id="1" name="ground" width="{width}" height="{height}">
      <data encoding="csv">
       {tile_data}
      </data>
     </layer>
     <layer id="2" name="day_sprites" width="{width}" height="{height}">
      <data encoding="csv">
       {empty_tile_data}
      </data>
     </layer>
     <layer id="3" name="night_sprites" width="{width}" height="{height}">
      <data encoding="csv">
       {empty_tile_data}
      </data>
     </layer>
     <objectgroup color="#ff0000" id="4" name="Events">
      {events}
     </objectgroup>
    </map>
    """)

_SPAWN_POINT_OBJECT = (
    '<object id="{oid}" type="spawn_point" x="{x}" y="{y}" '
    'width="16" height="16"/>'
)

_ENCOUNTER_ZONE_OBJECT = textwrap.dedent("""\
    <object id="{oid}" type="encounter_zone" x="{x}" y="{y}"
            width="{w}" height="{h}">
     <properties>
      <property name="monster_ids" value="{monster_ids}"/>
     </properties>
    </object>""")

_NPC_OBJECT = textwrap.dedent("""\
    <object id="{oid}" type="npc" x="{x}" y="{y}"
            width="16" height="32">
     <properties>
      <property name="script_id" value="{script_id}"/>
     </properties>
    </object>""")

_TRANSITION_OBJECT = textwrap.dedent("""\
    <object id="{oid}" type="map_transition" x="{x}" y="{y}"
            width="16" height="16">
     <properties>
      <property name="target_map" value="{target_map}"/>
     </properties>
    </object>""")

_SCRIPT_TEMPLATE = """\
{{
  "id": "{script_id}",
  "description": "{description}",
  "triggers": [{triggers}],
  "nodes": [{nodes}],
  "entry_node": {entry_node}
}}
"""

_LOCALE_TEMPLATE = textwrap.dedent("""\
    # Campaign locale file — {campaign_name}
    # Generated by OpenCapsuleMon Campaign Maker
    #
    [strings]
    {strings}
    """)


@dataclass
class CampaignTemplate:
    """
    Base campaign template. Subclasses override apply() to generate content.

    Attributes
    ----------
    name:
        Internal template identifier (matches STARTER_TEMPLATES in models.py).
    display_name:
        Human-readable name shown in the wizard UI.
    description:
        Short description shown in the wizard template preview.
    features:
        Bullet-point feature list shown in the wizard preview panel.
    """

    name: str
    display_name: str
    description: str
    features: list[str] = field(default_factory=list)

    def apply(
        self,
        scaffold_root: Path,
        campaign_id: str,
        campaign_name: str,
        author: str,
    ) -> list[Path]:
        """
        Populate *scaffold_root* with template content.

        Parameters
        ----------
        scaffold_root:
            The already-created campaign root directory (from wizard scaffold).
        campaign_id:
            The campaign's machine ID.
        campaign_name:
            The campaign's display name.
        author:
            The campaign author name.

        Returns
        -------
        list[Path]
            All files written by this template.
        """
        return []

    # ------------------------------------------------------------------
    # Shared helpers for subclasses
    # ------------------------------------------------------------------

    def _write_tmx(
        self,
        maps_dir: Path,
        slug: str,
        width: int = 20,
        height: int = 20,
        events_xml: str = "",
    ) -> Path:
        """Write a minimal valid TMX map file and return its path."""
        tile_count = width * height
        tile_data = ",".join(["1"] * tile_count)
        empty_tile_data = ",".join(["0"] * tile_count)

        content = _TMX_TEMPLATE.format(
            slug=slug,
            width=width,
            height=height,
            tile_data=tile_data,
            empty_tile_data=empty_tile_data,
            events=events_xml or "",
        )
        path = maps_dir / f"{slug}.tmx"
        path.write_text(content, encoding="utf-8")
        logger.debug("Template wrote map: %s", path)
        return path

    def _write_script(
        self,
        scripts_dir: Path,
        script_id: str,
        description: str = "",
        trigger_type: str = "game_start",
        action_type: str = "dialog",
        action_args: Optional[dict] = None,
    ) -> Path:
        """Write a minimal event graph script file and return its path."""
        import json

        trigger = {"type": trigger_type, "args": {}}
        action_args = action_args or {"text_key": f"{script_id}.greeting"}
        node = {
            "id": "node_start",
            "action": action_type,
            "args": action_args,
            "next": None,
            "branches": {},
        }
        data = {
            "id": script_id,
            "description": description,
            "triggers": [trigger],
            "nodes": [node],
            "entry_node": "node_start",
        }
        content = json.dumps(data, indent=2)
        path = scripts_dir / f"{script_id}.json"
        path.write_text(content, encoding="utf-8")
        logger.debug("Template wrote script: %s", path)
        return path

    def _write_locale(
        self,
        locale_dir: Path,
        lang: str = "en_US",
        strings: Optional[dict[str, str]] = None,
    ) -> Path:
        """Write a locale strings file and return its path."""
        strings = strings or {}
        string_lines = "\n".join(f'{k} = "{v}"' for k, v in strings.items())
        content = _LOCALE_TEMPLATE.format(
            campaign_name=self.display_name,
            strings=string_lines,
        )
        path = locale_dir / f"{lang}.ini"
        path.write_text(content, encoding="utf-8")
        return path

    @staticmethod
    def _spawn_event(oid: int, x: int = 32, y: int = 32) -> str:
        return _SPAWN_POINT_OBJECT.format(oid=oid, x=x, y=y)

    @staticmethod
    def _encounter_event(
        oid: int,
        monster_ids: list[str],
        x: int = 0,
        y: int = 0,
        w: int = 200,
        h: int = 200,
    ) -> str:
        return _ENCOUNTER_ZONE_OBJECT.format(
            oid=oid,
            x=x,
            y=y,
            w=w,
            h=h,
            monster_ids=",".join(monster_ids),
        )

    @staticmethod
    def _npc_event(oid: int, script_id: str, x: int = 80, y: int = 80) -> str:
        return _NPC_OBJECT.format(oid=oid, script_id=script_id, x=x, y=y)

    @staticmethod
    def _transition_event(
        oid: int, target_map: str, x: int = 300, y: int = 150
    ) -> str:
        return _TRANSITION_OBJECT.format(
            oid=oid, target_map=target_map, x=x, y=y
        )
